name: CI

on:
  pull_request:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  check-lint:
    strategy:
      matrix:
        include:
          - name: code
            tox-env: check-lint
          - name: documentation
            tox-env: docs

    name: Check ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          set -xeu
          python -VV
          pip install tox
      - name: Check ${{ matrix.name }}
        run: tox -e ${{ matrix.tox-env }}

  tests:
    strategy:
      matrix:
        include:
          - python-version: 3.6
            tox-env: py36-tests
            auth-method: token
          - python-version: 3.7
            tox-env: py37-tests
            auth-method: token
          - python-version: 3.8
            tox-env: py38-tests
            auth-method: token
          - python-version: 3.8
            tox-env: py38-tests
            auth-method: userpass
          - python-version: 3.8
            tox-env: py38-tests
            auth-method: cert

    name: Test (python ${{ matrix.python-version }} / ${{ matrix.auth-method }})
    runs-on: ubuntu-latest

    services:
      vault:
        image: ewjoachim/vault-cli-dev
        ports:
          - "8200:8200"
          - "8443:8443"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          set -xeu
          pwd
          python -VV
          ./dev-env auth ${{ matrix.auth-method }}
          pip install tox
      - name: Run tox targets for ${{ matrix.python-version }}
        run: tox -e ${{ matrix.tox-env }}
        env:
          PYTEST_ADDOPTS: "--cov-report=xml"
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  report-status:
    name: success
    runs-on: ubuntu-latest
    needs:
      - check-lint
      - tests
    steps:
      - name: Report success
        run: echo 'Success !'
